### ISSUE TITLE
Make migration 0006 depend on easy_thumbnails.0002

### ISSUE THREAD

**Issue by rvanlaar** [divio/django-filer#1009]
I can't run a `manage.py migrate` because it crashes on the easy_thumbnails tables not being there.

Please add a dependency from the 0006 migrations to the easy_thumbnails.0002 migration.

**Comment by IlianIliev** [comment]
I am unable to reproduce this issue. In addition tried to run only the `filer` migration without running the `easy_thumbnails` migrations and it works fine. Can you give more information?

**Comment by rvanlaar** [comment]
Alright thanks for trying. For me it crashed. I've moved on.
