### ISSUE TITLE
hidden_input field of AdminFileWidget is showing on Django 1.11

### ISSUE THREAD

**Issue by marcosguedes** [divio/django-filer#1018]
FilerImageFields show an extra section

![image](https://user-images.githubusercontent.com/6418368/32493964-aef5aa2e-c3b7-11e7-831d-caad862f57cd.png)

I'm using Django CMS and django-extensions

I've managed to fix this by overriding `admin/filer/widgets/admin_file.html` and wrapping `{{ hidden_input }}` on a hidden element

`<p style="display: none">{{ hidden_input }}</p>`

So far it's working. Am I doing something wrong or is this a bug?

Thanks

**Comment by jrief** [comment]
@marcosguedes there is a pending pull request for this, see #987

**Comment by marcosguedes** [comment]
Thank you! I couldn't find it searching

**Comment by marcosguedes** [comment]
#987

**Comment by marcosguedes** [comment]
It's not really fixed so maybe I shouldn't be closing this issue...

**Comment by marcosguedes** [comment]
Pull request merged. Closing
