### ISSUE TITLE
Is there a way how to fix styles issues?

### ISSUE THREAD

**Issue by dmnBrest** [divio/django-filer#1027]
I try to implement Django-Filer to my project, but there a lot of css issues.
How can I override styles of template to include custom style fixes.
I use Django 1.11 (for Django 2 it even )
I have already provided css fixes in admin interface but how can I add styles for this popup? And what is this second button right after Choose File (it open popup with file names and not change anything on select in parent window)?

![image](https://user-images.githubusercontent.com/7594309/34079498-d59671c0-e33f-11e7-8646-eb64191eaf8b.png)

**Comment by lidymonteirowm** [comment]
I have the same problem :(

**Comment by SteinRobert** [comment]
You can just create a template folder:
`templates/admin/filer/widgets/admin_file.html` and insert the HTML from the latest [admin_file.html](https://github.com/divio/django-filer/blob/develop/filer/templates/admin/filer/widgets/admin_file.html). It already contains a fix but is not included in the latest release.
This fixes the button without content at least.

**Comment by jedie** [comment]
> It already contains a fix but is not included in the latest release.

When will the new version be released?

**Comment by yakky** [comment]
1.3.1 is on its way. I will release it tomorrow at the latest
Thanks all for reporting and investigating
