### ISSUE TITLE
hide "Save as New" button

### ISSUE THREAD

**Issue by jedie** [divio/django-filer#1035]
A click on "Save as New" will raise into PermissionDenied, because filer.admin.permissions.PrimitivePermissionAwareModelAdmin.has_add_permission() will always return False, see: https://github.com/divio/django-filer/blob/develop/filer/admin/permissions.py#L9

So, the "Save as New" button should not be exists...

**Comment by yakky** [comment]
Confirmed

**Comment by joncasdam** [comment]
PR https://github.com/divio/django-filer/pull/1077 opened.
