### ISSUE TITLE
Django 1.11: new ForeignKeyRawIdWidget rendering breaks AdminFileWidget rendering with related_url

### ISSUE THREAD

**Issue by nmashton** [divio/django-filer#1040]
When moving from Django 1.10 to Django 1.11, the form widget for a `FilerImageField` (namely `AdminImageWidget`, which extends `AdminFileWidget` without modification) starts rendering with a visible `a.related-lookup` link:

![image](https://user-images.githubusercontent.com/1625749/36980556-a448ef98-2058-11e8-8d35-8bddc98e3220.png)

In Django 1.10, this element is not present (not just invisible but actually not rendered):

![image](https://user-images.githubusercontent.com/1625749/36980738-3215fd3e-2059-11e8-92ba-e57e66f4fcb1.png)

The corresponding model field involved here is (with hopefully irrelevant names changed):

```
name_of_field = FilerImageField(blank=False, null=False,
        related_name="the_fields_related_name")
```

It seems that [this part](https://github.com/divio/django-filer/blob/2e2deff1c8000a710ea9b2836afccfe365e3f8d7/filer/fields/file.py#L57) of the AdminFileWidget's `render` method relies on features of the rendering of `ForeignKeyRawIdWidget` that go away in Django 1.11:

```
# rendering the super for ForeignKeyRawIdWidget on purpose here because
# we only need the input and none of the other stuff that
# ForeignKeyRawIdWidget adds
hidden_input = super(ForeignKeyRawIdWidget, self).render(name, value, attrs)
```

In the transition to a new `ForeignKeyRawIdWidget` (now with its own template, `'admin/widgets/foreign_key_raw_id.html'`), it seems the `a.related-lookup` element gets added where it previously did not. Why that is the case (seeing as `if rel_to in self.admin_site._registry` is the condition in both the old and new ways of rendering the widget) I haven't quite figured out as of the filing of this issue.

**Comment by benzkji** [comment]
can confirm.

**Comment by SteinRobert** [comment]
I haven't checked but I guess this is related to #987, #1018 and #1027.
So the fix is already merged but still needs to be released.

**Comment by yakky** [comment]
Thanks for reporting
I should be able to release 1.3.1 over the next few days

**Comment by yakky** [comment]
Closing, 1.3.1 is on its way
