### ISSUE TITLE
django-mptt<0.9

### ISSUE THREAD

**Issue by batisteo** [divio/django-filer#1070]
Is there any good reason to limit django-mptt to `<0.9`?

**Comment by liminspace** [comment]
`django-mptt 0.9` supports Django 1.11 and 2.0 but removed tests of supporting 1.9, 1.10.
@czpython, check tests and move the django-mptt limit to `<0.10` if everything is ok and release new minor version. Everybody wants to upgrade their django to 1.11 at least ;)

**Comment by yakky** [comment]
Sounds sensible
PR Added
