### ISSUE TITLE
Thumbnails not visible for files with permission enabled

### ISSUE THREAD

**Issue by steveputman** [divio/django-filer#1083]
Using the FILER_STORAGES dictionary below, I'm getting some odd behavior: I can't tell whether it's misconfiguration or a bug. I am able to see the underlying file with permissions enabled, and thumbnails are generated and seem to match up path-wise with what's expected. And when I disable permissions on a file, both the thumbnail and the underlying file are visible. Any ideas what I'm doing wrong?

```python
FILER_STORAGES = {
    'public': {
        'main': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {
                'location': MEDIA_ROOT,
                'base_url': FILER_PUBLIC_URL,
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': '',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PublicFileSystemStorage',
            'OPTIONS': {
                'location': MEDIA_ROOT,
                'base_url': FILER_PUBLIC_URL,
            },
            'THUMBNAIL_OPTIONS': {
                'base_dir': 'thumbnails',
                },
        },
    },
    'private': {
        'main': {
            'ENGINE': 'filer.storage.PrivateFileSystemStorage',
            'OPTIONS': {
                'location': FILER_PRIVATE_ROOT,
                'base_url': FILER_PRIVATE_URL,
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': '',
        },
        'thumbnails': {
            'ENGINE': 'filer.storage.PrivateFileSystemStorage',
            'OPTIONS': {
               'location': FILER_PRIVATE_ROOT,
               'base_url': FILER_PRIVATE_URL,
            },
            'THUMBNAIL_OPTIONS': {
                'base_dir': 'thumbnails',
                },
        },
    },
}
```

**Comment by benzkji** [comment]
I've made the same experience, in another setup though. In general, as I read docs, it seems it was more made for "Downloads", and less for images ( https://django-filer.readthedocs.io/en/latest/secure_downloads.html ) - and, probably will stay beta for some time.

Though still, as code suggests, it probably should work anyway:  
https://github.com/divio/django-filer/blob/develop/filer/server/thumbnails_server_urls.py  
https://github.com/divio/django-filer/blob/develop/filer/server/views.py

No time to dive in right now, but curious about your findings!

**Comment by steveputman** [comment]
Closing, because I'm chalking this up to poor configuration on my part. Everything works fine using the django-filer defaults.

**Comment by monim67** [comment]
Having the same issue with default configuration. I don't have a `FILER_STORAGES` setting in my settings file.
I am using following package versions.

```
django-cms==3.8.0
djangocms-file==3.0.0
djangocms-picture==3.0.0
easy_thumbnails==2.7.1
django-filer==2.0.2
```
