### ISSUE TITLE
Uncaught ReferenceError: django is not defined

### ISSUE THREAD

**Issue by ViggieSmalls** [divio/django-filer#1103]
When I try to create a new model with the content creation wizard that has a FilerImageField, I get an `Uncaught ReferenceError: django is not defined` at:

    VM1967 dropzone.init.js:11
    VM1969 popup_handling.js:46
    VM1970 widget.js:4
    (index):155

Why do I get this and how can I avoid it?

#### modify `aldryn_newsblog/cms_wizards.py`:

    class CreateNewsBlogArticleForm(BaseFormMixin, TranslatableModelForm):
        # ...
        class Meta:
            model = Article
            fields = ['title', 'app_config', 'featured_image']
        # ...

#### or: create a test `foo` app:

My `models.py` file:

    from django.db import models
    from django.core.urlresolvers import reverse
    from filer.fields.image import FilerImageField

    class Foo(models.Model):
        slug = models.SlugField(unique=True)
        image = FilerImageField(related_name='foo_picture', null=True)

        def get_absolute_url(self):
            return reverse('foo', kwargs={'slug': self.slug})

My `forms.py` file:

    from django import forms
    from .models import Foo

    class FooWizardForm(forms.ModelForm):
        class Meta:
            model = Foo
            exclude = []

My `cms_wizards.py` file:

    from cms.wizards.wizard_base import Wizard
    from cms.wizards.wizard_pool import wizard_pool
    from .forms import FooWizardForm

    class FooWizard(Wizard):
        pass

    foo_wizard = FooWizard(
        title="Foo",
        weight=200,
        form=FooWizardForm,
        description="Create a new Foo"
    )

    wizard_pool.register(foo_wizard)

My `views.py` file:

    from django.views.generic import DetailView
    from .models import Foo

    class FooView(DetailView):
        model = Foo

My `urls.py` file:

    from foo.views import FooView
    from django.conf import settings
    from django.contrib import admin
    from django.conf.urls import url, include
    from django.conf.urls.static import static

    urlpatterns = [
        url(r'^admin/', admin.site.urls),
        url(r'^foo/(?P<slug>[-\w]+)/$', FooView.as_view(), name='foo'),
        url(r'^', include('cms.urls'))
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

**Comment by stefanw** [comment]
The problem here is that Filer's `AdminFileWidget` [does not have an explicit dependency on Django's jQuery instance](https://github.com/divio/django-filer/blob/master/filer/fields/file.py#L84-L95), but it should. The [order of media assets in Django](https://docs.djangoproject.com/en/2.1/topics/forms/media/#order-of-assets) is important and Django's jQuery should be referenced atop so it can be merged and rendered before `dropzone.min.js`. Here's how I [monkey patched it](https://github.com/okfde/fragdenstaat_de/blob/master/fragdenstaat_de/fds_blog/apps.py#L9-L14).
