### ISSUE TITLE
Make autocrop easy-thumbnails processor subject location aware

### ISSUE THREAD

**Issue by mitar** [divio/django-filer#111]
Currently autocrop processor is not subject location aware so it can autocrop the image and later on scale and crop processor can use wrong subject location coordinates. I am proposing that we implement our own autocrop processor which, if it crops anything, stores the crop bounding box into the image object itself (as some internal attribute). And then scale and crop processor can find this information and correct the subject location information.

Or we can implement a new processor which should be added to the beginning of the processors list which would just store subject location in the image object. Then all subject location aware processors could modify this information as they are processing the image.

**Comment by Darex1991** [comment]
Anyone will answer for this ticket?
