### ISSUE TITLE
Django 2.1 render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by vThaian** [divio/django-filer#1120]
I'm getting an error:
`render() got an unexpected keyword argument 'renderer'`

Django from version 2.1 requires `renderer` argument for render method:

> Support for Widget.render() methods without the renderer argument is removed.

`AdminFolderWidget` and `AdminFileWidget` classes are missing `renderer` argument - so it should be added to support Django 2.1 and up.

Here is my PR to fix that: #...

Filer: 1.4.1
Django: 2.1

**Comment by chisvi** [comment]
It seems that you made a typo in #1121, AdminFileWidget now receives render argument instead of renderer. I've fixed it on #1123.

**Comment by vThaian** [comment]
@chisvi thanks for your comment. Yes, you are right.
