### ISSUE TITLE
Multi-tenant

### ISSUE THREAD

**Issue by KrunchMuffin** [divio/django-filer#1132]
Any chance this is multi-tenant?

**Comment by debaze** [comment]
You could use a separate Django package, like djang-tenants, to allow for multi-tenancy. Then you place the filer app under 'tenant apps'. You could also separate the uploads by separating media files for each tenant.

**Comment by KrunchMuffin** [comment]
can you use django-tenants for one app? Thought it was for the whole project?

**Comment by debaze** [comment]
Yes. You install django-tenants into your project like any other package,
but in settings you choose which apps of your project are public and which
are tenant-specific (different db schema for each tenant)

Op vr 8 feb. 2019 om 16:51 schreef Derek <notifications@github.com>:

**Comment by KrunchMuffin** [comment]
OK, what about easy_thumbnails, mptt, would those be tenant specific as they are required for filer?
