### ISSUE TITLE
Provide file sha/hash?

### ISSUE THREAD

**Issue by stuaxo** [divio/django-filer#1135]
Every time I write some sort of ingester, I like to avoid inputting content that already exists.

Usually I'll do this with something like sha256.    Is there any chance django-filer could provide an API to get a hash of a file (as well as automatically store these on upload) ?

Places like S3 already provide an md5 via the etag, which could be worth hooking into.

**Comment by ianare** [comment]
There already is a column "sha1" in the table "filer_file" that is populated automatically but it's not displayed in the admin unfortunately.

**Comment by stuaxo** [comment]
Cheers.

I'll probably have a table somewhere to map sha1s to the etag value s3 uses - is a place I can hook into, to run code after images are saved + calculate this ?
