### ISSUE TITLE
Error after updating to Django 2.2

### ISSUE THREAD

**Issue by kaduuuken** [divio/django-filer#1142]
for class FilerFileField:
`TypeError: __init__() missing 1 required positional argument: 'on_delete'`

since Django expects the `on_delete` parameter since 2.0

**Comment by kaduuuken** [comment]
misunderstanding

**Comment by andreasnuesslein** [comment]
Hm - I have the same issue, I think; can you tell me what the misunderstanding is? :D 

cheers

**Comment by andreasnuesslein** [comment]
Ah!, the `FilerImageField` that I use needs the on_delete :+1:

**Comment by bmassot** [comment]
I just had the same issue. I believe django-filer's doc should be clear about on_delete having to be used.
