### ISSUE TITLE
Prominent example of saving a file.

### ISSUE THREAD

**Issue by stuaxo** [divio/django-filer#1164]
I only use files in django every few years (and filer even less) + have to go searching to work out how to make it work.

It would be good if django-filer had examples right on the front page of the docs, including a really basic "save a file", with content uploaded from a local file, or streamed from a request (if that is even an API provided by filer).

Cheers :)

**Comment by stuaxo** [comment]
For the record, I found this page https://vinta.ws/code/read-and-save-file-in-django-python.html useful, and ended up with something like this:

```
r = requests.get(url, stream=True)
im = Image.objects.create(file=ContentFile(r.content), name=name)
im.save()
```

**Comment by stuaxo** [comment]
Edit:  it turns out my example is incorrect :)  will update when I have one that actually uploads something.

**Comment by stuaxo** [comment]
Currently I have:

`
    r = requests.get(url)
    
    with NamedTemporaryFile('w+b', delete=True) as img_temp:
        img_temp.write(r.content)
        img_temp.flush()

        im = Image.objects.create(file=File(img_temp), name=name)    
        im.save()
`

**Comment by bigbobah** [comment]
hey @stuaxo! Having currently the same question. Have you succeed with it?

**Comment by bigbobah** [comment]
Actually, trying to store the uploaded file with django rest framework

**Comment by stuaxo** [comment]
I need to see if it works when using a different storage backend before I can say if it works properly.

**Comment by stuaxo** [comment]
Hi @bigbobah 
I can confirm the code above works the setup we have here, using boto + s3 as the backend.

Cheers.
