### ISSUE TITLE
FEATURE REQUEST: Adding support for WEBP images

### ISSUE THREAD

**Issue by AnderUstarroz** [divio/django-filer#1168]
Current version of **Django Filer doesn't support Webp images**. WebP lossless images are 26% smaller in size compared to PNGs and WebP lossy images are 25-34% smaller than comparable JPEG images at equivalent quality. It's probably going to become a web standard at some stage, therefore adding support for this format would be a great improvement.

**Comment by jrief** [comment]
Before adding Webp support to django-filer, we need that in [easy-thumbnails](https://easy-thumbnails.readthedocs.io/en/stable/). So please ask there first. If Pillow supports webp, then creating a pull request on easy-thumbnails will not be that hard.

**Comment by AnderUstarroz** [comment]
Thanks for your quick answer @jrief, I have added a [Feature request in easy-thumbnails repository](https://github.com/SmileyChris/easy-thumbnails/issues/528). I will update this thread when I get news from them.

**Comment by jrief** [comment]
Using WebP with django-filer actually is quite easy. Here is a [short instruction](https://easy-thumbnails.readthedocs.io/en/latest/ref/webp/).
That said, django-filer does not support WebP natively. This means that the source (or canonical image) mus be in a format supported by ~100% of all browsers, currently ~80%. Whenever we reach that point, let's discuss this again.

**Comment by corentinbettiol** [comment]
If you want to generate webp thumbnails, you can use these settings (thanks @benzkji):

```py
THUMBNAIL_EXTENSION = 'webp'
THUMBNAIL_TRANSPARENCY_EXTENSION = 'webp'
```

*That means you don't have to follow [this tutorial](https://easy-thumbnails.readthedocs.io/en/latest/ref/webp/) anymore.*

**Comment by benzkji** [comment]
@corentinbettiol not completly true. If you need compatibilty, you might still need to, as the settings above just output webp for everything ,-). Though there also is a shortcut, when providing the original image (unthumbnailed) as a fallback for non webp capable browsers, you'll not need any signals and the like. As most people still upload jpeg anyways, this can work very well. Only drawback is download size, as these jpges will be originals, and probably quite heavy ;)

**Comment by fsbraun** [comment]
Also, as of version 3.0 filer will accept the WebP format for uploaded images, too (the source format). 

This might be interesting if you want to manually control the format images are delivered: With `THUMBNAIL_PRESERVE_EXTENSIONS = ('webp',)` all WebP uploads would be delivered as WebP.
