### ISSUE TITLE
update dependency for django-polymorphic

### ISSUE THREAD

**Issue by wfehr** [divio/django-filer#1177]
The current version of django-polymorphic is 2.1.2, which can't be installed because django-filer only allows its version to be <2.1.

Version 2.1 adds support vor django 2.2.

The problem is that you now can't properly install projects which depend on django-polymorphic<2.2 if django-filer==1.6 (for example) is installed.

polymorphic==2.0.3 (which gets installed with current filer-version) has some problems in the admin interface where you can't add some models for example.

**Comment by jrief** [comment]
In the [next release](https://github.com/divio/django-filer/blob/33bd163c403ad861c3883ba1143b9a2594b8e652/setup.py#L11), this will be fixed.

**Comment by wfehr** [comment]
Is there a date when the next version will be released?

Django 2.1 is no longer supported (as seen in the 2.1 docs at the top).

**Comment by wfehr** [comment]
1.7.0 was released 2 weeks ago, support was added there.
