### ISSUE TITLE
Upload multiple files to a model

### ISSUE THREAD

**Issue by mezitax** [divio/django-filer#1181]
I would like to upload multiple files to a model in the frontend without having to write one field per file in the model.
A first approach to adding multiple files to the "Assignment" model would be like this:
```
class Assignment(models.Model):
    name = models.CharField(verbose_name="Título", max_length=120, blank=False)

class Attachment(models.Model):
    attach = FilerFileField(verbose_name="Adjunto", null=True, blank=True, on_delete=models.SET_NULL, related_name="attachment_of_file")
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name="attachment_of_assignment")
```
But then I couldn't have the filer upload interface
Before using any snippet, is there a way to do this with filer?

**Comment by jrief** [comment]
Change your model to:

```python
class Attachment(models.Model):
    file = FilerFileField(
        verbose_name="Adjunto",
        on_delete=models.CASCADE,
        related_name="attachment_of_file",  # not required
    )

    assignment = models.ForeignKey(
        'myproject.Assignment',
        on_delete=models.CASCADE,
        related_name="attachment_of_assignment",  # not required
    )

class Assignment(models.Model):
    name = models.CharField(
        verbose_name="Título",
        max_length=120,
        blank=False,
    )

    attachments = models.ManyToManyField(
        filer.File,
        through=Attachment,
    )
```

you can also try to do it directly, without the many2many "though"-class.

**Comment by derek-adair** [comment]
@jrief I'm unable to get this to work, however, the problem could be as simple as updating my imports.  First I tried (basically) copying/pasting this solution to my own code and importing filer.  Your imports are not shown so i'm not sure if you're importing something as filer, but the current version does not have an attribute "File"; throwing an error accordingly.

I also tried importing `from filer.models.filemodels import File` but this throws:

```
  File "/virtualenv/lib/python3.7/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration {{my_migration_name}} dependencies reference nonexistent parent node ('filer', '0013_auto_20210814_1619')
```

Not sure where to go from here.  Am I not importing the right model?
