### ISSUE TITLE
By default, upload files into last used folder

### ISSUE THREAD

**Issue by jrief** [divio/django-filer#1183]
Currently, if someone uploads a file using drag and drop on a widget, it is stored inside the special folder named "Unsorted Files". In large installations, this gives a bad user experience. One would expect such a file in the last used folder, which in django-filer is handled by the session variable `filer_last_folder_id`.

By adding one line in `filer.admin.clipboardadmin.ajax_upload()`, this could be fixed.

Please comment on this feature proposal.

**Comment by niz11** [comment]
Or a default public folder. At the moment the files are "unsorted", which means they don't have a folder.
They won't show in the search results (If FILER_ENABLE_PERMISSIONS = True), for users that aren't Admins. I wrote a migration to move all the files to the "public" folder, but I feel like it should be a default.

Another issue I didn't find an answer to yet. How to choose a default folder, that Filer would open in. At the moment the default is "Unsorted", which means no folder. Users just drag and drop by default to Unsorted.

**Comment by jrief** [comment]
@niz11 django-filer sets a session variable named `filer_last_folder_id `. It's intention is, that when opening a folder, one gets the latest used folder.

I don't like the idea of a public folder accessible be everybody. We have 200+ departments and if everybody would upload its files into that folder, then forgets to move them to an appropriate place, we would get a big mess. Also consider people uploading a file via drag&drop and not caring about where it lands.

**Comment by niz11** [comment]
Hmm well at the moment here, everyone drag and drops to "Unsorted folder". Not being able to find pictures, causes users to upload duplicates of the same picture. 
The hard part would be to communicate that everyone would switch to the public folder I created and then your change would be perfect.

**Comment by jrief** [comment]
Having a folder named "public" instead of "unsorted", doesn't change the main problem.

Many CMS users just don't care in which logical folder their pictures are stored, so they just upload them.
