### ISSUE TITLE
Unable to upload multiple images/files

### ISSUE THREAD

**Issue by pupattan** [divio/django-filer#1187]
Unable to upload multiple images/files at time

**Comment by jrief** [comment]
please explain step by step on how to reproduce this.

**Comment by pupattan** [comment]
i am trying to upload multiple files 
![image](https://user-images.githubusercontent.com/19246595/79729089-98863580-830c-11ea-87c8-618eeebaee11.png)

Clicking on upload files only allowing me to upload one file at a time.
![image](https://user-images.githubusercontent.com/19246595/79729177-b81d5e00-830c-11ea-9af9-d7494d6e0523.png)

But how to upload multiple files at a time ? 
While i am trying to drag and drop it shows error

**Comment by jrief** [comment]
> While i am trying to drag and drop it shows error

it's not very insightful if you don't tell us which error. Please also check your browser console.

**Comment by pupattan** [comment]
When i click on upload button , i can not select/browse multiple files at once.

**Comment by remoover** [comment]
I am also facing the same problem . Trying to find how to upload multiple pictures... IT WILL BE HELPFUL !!

**Comment by pupattan** [comment]
I am trying to drop multiple files . getting the console error.
![image](https://user-images.githubusercontent.com/19246595/79963933-a15f3e80-84a7-11ea-90e2-b5c65b0f145f.png)

**Comment by jrief** [comment]
Please recheck with version 1.7.1

**Comment by pupattan** [comment]
This is working on latest versions
