### ISSUE TITLE
JQuery loaded by File polluting the global namespace when DEBUG = False

### ISSUE THREAD

**Issue by mrlowe** [divio/django-filer#1188]
Encountered as a problem while using Mezzanine.

This was a regression introduced in b66a42b. Basically it causes jquery.js to be loaded after jquery.init.js when not in DEBUG.

Two-line fix, PR incoming.

**Comment by jrief** [comment]
This is required for all Django>2 installations. Which Django version are you using?

**Comment by mrlowe** [comment]
@jrief we're using 1.11, but if we inject "jquery.min.js" when in non-debug (the way django does) we should be fine.

**Comment by jrief** [comment]
Fixed in version 1.7.1
