### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by oluwakayode-a** [divio/django-filer#1204]
Hello,
I get this error whenever I try to run 'python manage.py migrate'

File "C:\Python38\lib\site-packages\filer\fields\file.py", line 136, in __init__
    super(FilerFileField, self).__init__(**kwargs)
TypeError: __init__() missing 1 required positional argument: 'on_delete'

Any help would be appreciated.

**Comment by oluwakayode-a** [comment]
```
class FilerFileField(models.ForeignKey):
    default_form_class = AdminFileFormField
    default_model_class = File

    def __init__(self, **kwargs):
        # We hard-code the `to` argument for ForeignKey.__init__
        dfl = get_model_label(self.default_model_class)
        kwargs.setdefault('on_delete', models.CASCADE) # adding this line fixed the problem.

```
Can this be incorporated into the library?
Fix gotten from this link [https://code.djangoproject.com/ticket/22846](url)

**Comment by yakky** [comment]
as with Django `ForeignKey` no default is provided, because develop must make a conscious decision regarding the on_delete behavior

You must explicitly declare the behavior when using the field

```python
my_file = FilerFileField(on_delete=models.PROTECT)
```
