### ISSUE TITLE
Tag management

### ISSUE THREAD

**Issue by FinalAngel** [divio/django-filer#1208]
@yakky or @jrief we have a weird tag system where 2.x tags and 3.x tags are around, can those be deleted? It creates now conflict with 2.0.0

**Comment by jrief** [comment]
Really weird! I just deleted all tags down to 1.0.0 which did have an unrelated revision history.

You should be able to create 2.0.0 now.
Btw.: The proper version string according to PEP 440 would be to tag it 2.0 and not 2.0.0.
