### ISSUE TITLE
Better error handling if uploads fail

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#298]
**Fails if**

* PIL is compiled without JPEG support, django-filer fails to resize jpegs.
* Same happens if the process does not have enough permissions to write files to disc.

The upload fails subtly and the only visible error to the uploader is a file in the clipboard called "Undefined Undefined".

Filer should fail with a useful error message instead.

Also see #257.

**Comment by stefanfoulis** [comment]
Since the redesign, it actually shows a success message in these cases, even if the upload POST caused a 500 error.

**Comment by lory87** [comment]
Hi @stefanfoulis and @hostitlocal 
This issue is solved in current filer version 1.2.0. Will close it.
