### ISSUE TITLE
Mismatched double quotes in admin template

### ISSUE THREAD

**Issue by qris** [divio/django-filer#353]
https://github.com/stefanfoulis/django-filer/blob/develop/filer/templates/admin/filer/widgets/admin_file.html line 17:

    <img id="{{ clear_id }}" src="{% admin_icon_base %}icon_deletelink.gif" width="10" height="10" alt="{% trans 'Clear' %}" title="{% trans 'Clear' %}"{% if not object %} style="display: none;"{% endif %}" />

Note the final doublequote after `{% endif %}`, which doesn't match anything. There is a similar one on https://github.com/stefanfoulis/django-filer/blob/develop/filer/templates/admin/filer/widgets/admin_folder.html line 10:

    <img id="{{ clear_id }}" src="{% admin_icon_base %}icon_deletelink.gif" width="10" height="10" alt="{% trans 'Clear' %}" title="{% trans 'Clear' %}"{% if not object %} style="display: none;"{% endif %}" />

**Comment by lory87** [comment]
Hi @qris Can we close this issue? According to referenced pull requests is this issue fixed. Thank you for your feedback.

**Comment by qris** [comment]
Looks to be fixed, thanks!
