### ISSUE TITLE
Missing @2x icons in static folder

### ISSUE THREAD

**Issue by topiaruss** [divio/django-filer#410]
At least the following are missing:
  /static/filer/icons/unfiled_folder_48x48@2x.png
  /static/filer/icons/plainfolder_48x48@2x.png
  /static/filer/icons/file_48x48@2x.png
  /static/filer/icons/unfiled_folder_32x32@2x.png

But there are probably others missing, too.  I guess that some testing is happening on non retina displays, so this has not been spotted.

**Comment by mistalaba** [comment]
Thanks for a great package, this has helped me in several projects.

Just letting you know that the @2x files are still missing.

Cheers!

**Comment by lory87** [comment]
Hi @topiaruss, @jrief, @chris-erickson and @mistalaba 

The missing @2x icons are added and merged to develop branch. They will be in the next release.
