### ISSUE TITLE
Get absolute url

### ISSUE THREAD

**Issue by bbcreatv** [divio/django-filer#457]
Sorry this is not really an issue. Is it possible to get the absolute url, of a file just uploaded with Filer?

My problem is this: 

I'm using Django filer to upload music. I then want to submit this file to Django Celery to upload to Mixcloud using their API. But I can't figure out how to get url of the file. I'm not using views, I want to just use the admin. 

Is this possible?

Thanks!

**Comment by vstoykov** [comment]
I think that this issue need to be closed
