### ISSUE TITLE
[Extending Filer] Select a valid choice error

### ISSUE THREAD

**Issue by EliaContini-TR** [divio/django-filer#512]
Hi,

I'm trying to create a filer extension to manage PDF files using the documentation example ( http://django-filer.readthedocs.org/en/latest/extending_filer.html). At the moment the only change I've performed is

`filename_extensions = ['.pdf',]`

in the `matches_file_type function`.

When I try to use the plugin to select a PDF from an existing folder, I got this form error

`Select a valid choice. That choice is not one of the available choices.`

No errors or warnings in logs. I'm using Django 1.7.7 and djangoCMS 3.0.12.

Any idea about a possible cause?

Thank you

**Comment by BertrandBordage** [comment]
(**Can be closed**, here’s why:)

Hi @EliaContini-TR,

I just faced the same issue, and found the reason: You have to add the path to your model to the `FILER_FILE_MODELS` settings, **before** ``'filer.models.filemodels.File',`` because this generic file model matches any extension. So you should have something like this:
```python
FILER_FILE_MODELS = (
    'filer.models.imagemodels.Image',  # This can also be a custom image model
    'yourapp.models.YourModel',
    'filer.models.filemodels.File',
)
```

**Comment by lory87** [comment]
gentle ping @EliaContini-TR Can we close this issue? Thank you for your feedback.

**Comment by EliaContini-TR** [comment]
Hi guys,
I missed the notification, sorry.
Yes, this issue is closed for me.

Thank you

**Comment by lmanzurv** [comment]
Hi, I have the same issue but with SVG file. I already added the FILER_FILE_MODELS property in settings, and it allows me to upload the file but not to select it in the CMS plugin, resulting in the same 'invalid choice' error.

What could it be?

**Comment by creimers** [comment]
Boy oh boy oh boy oh boy. 

I was hitting the exact same wall just now.

It turns out that the `FILER_FILE_MODELS` settings entry is expecting the model references in a notation that was a little surprising to me:

```
FILER_FILE_MODELS = [
    "vineyard.GeoTIFF",
    "vineyard.GeoJSON",
    "filer.Image",
    "filer.File",
]
```

Using this notation solved the problem for me.
