### ISSUE TITLE
Add another is missing

### ISSUE THREAD

**Issue by J0hn5mith** [divio/django-filer#552]
When I use a filer version > 9.8 the "Add another ..." link below my model admin inline disappears. 
![localhost_8000_de_admin_project_management_project_18_](https://cloud.githubusercontent.com/assets/856276/8520089/a757e8e0-23d7-11e5-80e6-eaa3fc7fb73b.png)
![localhost_8000_de_admin_project_management_project_18_ 2](https://cloud.githubusercontent.com/assets/856276/8520090/a75e897a-23d7-11e5-9dd6-c73ccab1b904.png)

My requirements file contains the following dependencies: 

django==1.5.12
South==1.0.2
psycopg2==2.6.1
Fabric==1.8.0
dreipol-django-fagungis==0.0.21
django-jenkins==0.14.1
pylint==1.0.0
pep8==1.4.6
Sphinx==1.2b3
django-apptemplates==0.0.1
django-suit==0.2.13
Pillow==2.8.2
django-cms==2.4.3
django-filer==0.9.5
django-reversion==1.7.1
django-compressor==1.3
django-sortedm2m==0.6.0
django-autoslug==1.7.2
djorm-ext-pgarray==0.6
django-model-utils==1.4.0
cmsplugin-filer==0.9.9
django-suit-ckeditor==0.0.2
Django-Select2==4.2.2
django-email-obfuscator==0.1.1
easy_thumbnails==1.4
django-lockdown==1.0

With both kind of versions I get a JavaScript error but not the same one. With version <=0.9.8 I get the error: 
`Uncaught TypeError: $(...).on is not a function`

With version >0.9.8 the following error appears:
`Uncaught type property can't be changed`

My eventual goal is to use version 0.9.11. Using a lower version is an option since then I have other issues. 

I'd be glad if someone could help me.

**Comment by stefanfoulis** [comment]
this should be fixed in latest develop. Please re-open if you still experience this issue.
