### ISSUE TITLE
How can I migrate Filer fields to plain django FileField?

### ISSUE THREAD

**Issue by jamescw** [divio/django-filer#578]
Some users of my application have complained that the django filer interface is "too complicated" having to first upload the file then place in a folder using the interface. I am now using a standard FileField on the same model and want to migrate the file paths over from the filer field, I will use a datamigration to do it but how do I assign the path from the filer field to the new file field?

**Comment by stefanfoulis** [comment]
As long as you're using the same storage backend for filer files and your new file field (the default) it should be pretty simple. Filer uses a FileField on the File model as well. So in the data migration you'll have to get the path (a simple string) from the File.file field and save it into your new plain file field directly on your model.
