### ISSUE TITLE
Widget.js causes error "type property can't be changed"

### ISSUE THREAD

**Issue by bitterjug** [divio/django-filer#582]
[This line](https://github.com/stefanfoulis/django-filer/blob/develop/filer/static/filer/js/widget.js#L16) in widget.js:

     $('.filerFile .vForeignKeyRawIdAdminField').attr('type', 'hidden');

Causes an error for me from Query:

      Uncaught Error: type property can't be changed

Might it be possible to just hide the field rather than changing its type?

**Comment by bitterjug** [comment]
Looks like this might be related to #552

**Comment by bitterjug** [comment]
Apparently jQuery < v1.9 [doesn't like you to change the type of an element](http://stackoverflow.com/questions/3526059/setting-the-type-attribute-of-an-input-does-not-work-with-jquery-attr-method#3526107) because it's not supported by (old versions of) IE.

As of jQuery 1.9 [you _may_ change an element's type](http://jquery.com/upgrade-guide/1.9/#quot-input-quot-attr-quot-type-quot-newvalue-in-oldie) provided the browser lets you.

**Comment by stefanfoulis** [comment]
this should be fixed in latest develop. Please re-open if you still experience this issue.
