### ISSUE TITLE
Icons don't exist for all default sizes

### ISSUE THREAD

**Issue by ipmb** [divio/django-filer#605]
`FILER_ADMIN_ICON_SIZES` defaults to `'16', '32', '48', '64'`, but default icons don't exist for all those sizes. I haven't done a full pass, but just saw an error about `plainfolder_16x16.png` not being found.

**Comment by ipmb** [comment]
Changing the setting to `[32, 48, 64]` seems to resolve the issue

**Comment by vstoykov** [comment]
This is related to #613

**Comment by lory87** [comment]
@ipmb and @vstoykov Icons are implemented in every size. New Filer Version is already released
