### ISSUE TITLE
Bug: render_filer_lookup_button

### ISSUE THREAD

**Issue by Croden** [divio/django-filer#610]
Tag registered only for "../lookup.html"
https://github.com/stefanfoulis/django-filer/blob/develop/filer/templatetags/filer_admin_tags.py#L21
used in "../admin_file.html"
https://github.com/stefanfoulis/django-filer/blob/develop/filer/templates/admin/filer/widgets/admin_file.html#L15
causing 500 error.

**Comment by czpython** [comment]
Hello, I'm not sure I follow.
The tag renders the lookup.html template and is used in admin_file.html.

**Comment by Croden** [comment]
There was {% render_filer_lookup_button %} in admin_file.html. File is now completly rewritten and not causing that bug anymore.
