### ISSUE TITLE
Arrows are missing in filer 1.0.4

### ISSUE THREAD

**Issue by nilssolanki** [divio/django-filer#612]
Dear django-filer team,

when browsing files in django-filer 1.0.4, the arrows seem to be missing (as well as the arrows to go back up one directory):

**0.9.12: Arrows are working:**
![django-filer_0 9 12_admin_style_screenshot_2](https://cloud.githubusercontent.com/assets/5477955/11443409/430666de-951d-11e5-97cf-71b2f87fd5fb.png)
![django-filer_0 9 12_screenshot_2](https://cloud.githubusercontent.com/assets/5477955/11443408/43064a0a-951d-11e5-9cd4-219c75b26da0.png)

**1.0.4: Arrows are missing**
![django-filer_1 0 4_admin_style_screenshot](https://cloud.githubusercontent.com/assets/5477955/11443407/4305fbae-951d-11e5-8af2-40dafed027a5.png)
![django-filer_1 0 4_screenshot](https://cloud.githubusercontent.com/assets/5477955/11443410/43094e4e-951d-11e5-9f63-a5171a20dfa4.png)

**Requirements for 1.0.4:**
```cmsplugin-filer==1.0.0
Django==1.8.4
django-admin-shortcuts==1.2.6
django-appconf==1.0.1
django-ckeditor==5.0.2
django-classy-tags==0.6.2
django-cms==3.1.3
django-filer==1.0.4
django-lockdown==1.1
django-mptt==0.7.4
django-polymorphic==0.7.2
django-sekizai==0.8.2
django-storages-redux==1.2.3
django-treebeard==3.0
djangocms-admin-style==1.0.6
easy-thumbnails==2.2.1
gunicorn==19.3.0
html5lib==0.9999999
nodeenv==0.13.4
opbeat==3.0.4
Pillow==2.9.0
psycopg2==2.6.1
six==1.10.0
Unidecode==0.4.18
wheel==0.24.0
```

Are we missing something or is this a bug? Or were the arrows just replaced with checkboxes?

**Comment by jgoettsch** [comment]
Is [djangocms-admin-style](https://github.com/divio/djangocms-admin-style) is overriding the CSS on those items?

**Comment by nilssolanki** [comment]
Thank you for getting back to us.

The 2nd and the 4th screenshot were taken without djangocms-admin-style.

It seems to be a general issue with the version of the django-filer: The first two screenshots were taken using 0.9.12 (it works, with and without djangocms-admin-style). The second two were taken in version 1.0.4 (it doesn't work, with and without djangocms-admin-style).

We can't revert back to 0.9.12, because then there are other components that fail in conjuncture with djangocms-admin-style (see missing buttons in the first screenshot, top right).

**Comment by stefanfoulis** [comment]
This should be fixed in develop and will be in the next release.
