### ISSUE TITLE
Templates refer to older style Django admin icons.

### ISSUE THREAD

**Issue by joshuajonah** [divio/django-filer#639]
All of the Django admin icons are now SVGs nd the links need to be updated to them somehow hopefully without breaking pre-1.9 versions.

For example:
https://github.com/divio/django-filer/blob/develop/filer/templates/admin/filer/widgets/admin_file.html#L24
refers to `admin/img/icon_deletelink.gif`. This file no longer exists in 1.9 and was replaced with `admin/img/icon-deletelink.svg`.

**Comment by stefanfoulis** [comment]
fixed in #670

**Comment by stefanw** [comment]
@stefanfoulis It looks like the `admin/img/icon_deletelink.gif` has made its way  back into the widget's template.

https://github.com/divio/django-filer/blob/develop/filer/templates/admin/filer/widgets/admin_folder.html#L18

**Comment by stefanfoulis** [comment]
🤦‍♂️

**Comment by stefanw** [comment]
This can lead to parts of the admin not rendering at all: if `ManifestStaticFilesStorage` is used, the referenced static file can't be found, an error is raised and suppressed by template rendering. In my case this did not render the Filer Folder Permissions Add page correctly, which made adding permissions impossible.

[See this similar issue in Django CMS](https://github.com/divio/django-cms/issues/6317)
