### ISSUE TITLE
New django-polymorphic release breaks django-filer

### ISSUE THREAD

**Issue by philippze** [divio/django-filer#653]
The setup.py of django-filer sais it requires django_polymorphic>=0.7. Yesterday, django-polymorphic 1.8 was released, so this will be installed.

This commit  
https://github.com/chrisglass/django_polymorphic/commit/c48d4f589bb564145fd6b7d1244c8f5b655049ed  
changes the way we must import the polymorphic models and managers.

As this is not yet reflected in any django-filer release, django-filer will not work together with the newest django-polymorphic.

A little change in the setup.py file should help for now.

**Comment by saeedsq** [comment]
I've faced the same issue.
Running `python manage makemigrations` with Python 2.7, django 1.8.7, django-filer 1.0.4, and django-polymorphic 0.8.0, I get the following error:

        File "...\site-packages\filer\models\filemodels.py", line 14, in <module>
            from polymorphic import PolymorphicModel, PolymorphicManager
    ImportError: cannot import name PolymorphicModel

**Comment by mikek** [comment]
This should be fixed in 8022761e912582c386d5fc1fff9d154e20df23d7 and in the 1.0.6 release.
