### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by apeace** [divio/django-filer#710]
I was surprised to notice that tests [aren't running for Django 1.9](https://github.com/divio/django-filer/blob/1ad2472fb67e4cfd1ded35426a70c4c67781a9b7/.travis.yml#L13).

I ran them, and they passed!

```
pip install tox
git clone git@github.com:divio/django-filer.git
cd django-filer/
tox -e py27-django19-thumbs2x
tox -e py27-django19-custom_image-thumbs2x
tox -e py27-django_master-thumbs2x
```

Just wanted to open this so we can track the status of Django 1.9 support. Thanks!

**Comment by apeace** [comment]
With this change I was able to get `tox -e frontend` to pass as well, using Django 1.9:

```
diff --git a/setup.py b/setup.py
index 3efab7f..82990c6 100644
--- a/setup.py
+++ b/setup.py
@@ -25,7 +25,7 @@ setup(
     author_email='stefan@foulis.ch',
     packages=find_packages(),
     install_requires=(
-        'Django>=1.5,<1.8.99',  # Django is known to use rc versions
+        'Django>=1.8,<1.9.99',  # Django is known to use rc versions
         'easy-thumbnails>=1.0,<2.4',
         'django-mptt>=0.6,<0.9',  # the exact version depends on Django
         'django_polymorphic>=0.7,<0.9',
```

I wasn't sure of a better way to configure this through `tox`.

**Comment by stefanfoulis** [comment]
thanks. we've added django 1.9 to the testsuite now
