### ISSUE TITLE
Refresh file list after upload

### ISSUE THREAD

**Issue by jakob-o** [divio/django-filer#711]
Hi,

it is very confusing that after an upload you will have to refresh the "untitled files" to see the newly uploaded image. Usually the workflow for a new object using the `FilerImage` is to select the image, likely a new image has to be uploaded and I want to be able to pick the newly uploaded image immediately without having to refresh the image list view by hand. I hope my I made the issue clear enough.

Regards

Jakob

**EDIT:** I was refering to version `1.0.6` and just had a look at `1.1.0` / master / develop. It looks to me as if it refreshes after successful upload here https://github.com/jakob-o/django-filer/blob/develop/filer/static/filer/js/addons/upload-button.js#L98. Unfortunately i can not find a upload button anymore (using `djangocms-admin-style==1.0.8`)?! Additionaly it would be nice to sort by modified date and maybe even redirect to the upload directory. That could be optionally configurable via a settings flag. Maybe something like this:
```
{% url "admin:filer-directory_listing-unfiled_images" as upload_url %}
window.location.replace('{{ upload_url }}?{% if is_popup %}_popup=1&{% endif %}order_by=-modified_at');
```

**EDIT 2:** I got it now (you can only upload within folders in the new version... Is this a bug or a feature?). It would probably still be convenient to add the sorting after an upload refresh.

**EDIT 3:** Created a PR https://github.com/divio/django-filer/pull/712 for the ordering.

**Comment by stefanfoulis** [comment]
@jakob-o regarding upload only within folder: yes, that is a design decision. It basically makes the Clipboard obsolete and prevents "unfiled files" for the most part.
I'll close this Issue. We'll have a look at your ordering pr. thanks a lot!
