### ISSUE TITLE
mptt doesn't seem to work with latest Filer

### ISSUE THREAD

**Issue by chris-erickson** [divio/django-filer#714]
I had to update filer to get over the first issue #653, which then reveals another:

`AttributeError: type object 'Manager' has no attribute 'from_queryset'` at `File "/var/www/venv/lib/python2.7/site-packages/mptt/managers.py", line 63, in <module>` which maybe is related [to this](https://github.com/django-mptt/django-mptt/issues/378)?  Here is some maybe relevant context:

```python
63	class TreeManager(models.Manager.from_queryset(TreeQuerySet)):
64	    """
65	    A manager for working with trees of objects.
66	    """
67	
68	    def contribute_to_class(self, model, name):
69	        super(TreeManager, self).contribute_to_class(model, name)
```

I'm using Django 1.6.11 and this only happens when bringing up a dev VM for the first time.  Our established VM's seem to have no issue with this.  This lends me to believe there is an incompatible grey area of filer/mptt/polymorphic that a fresh build up of the `requirements.txt` that breaks.  Any ideas?

*Update*: After a bit more comparison, I found that pinning polymorphic to `django-polymorphic==0.7.1` seems to be all that's needed to make this work.  Not sure what the actual *fix* is, if this isn't.

**Comment by yakky** [comment]
IIRC mptt 0.8 dropped support for django 1.6


On 25 January 2016 03:46:20 CET, Chris Erickson <notifications@github.com> wrote:
>I had to update filer to get over the first issue #653, which then
>reveals another:
>
>`AttributeError: type object 'Manager' has no attribute
>'from_queryset'` at `File
>"/var/www/venv/lib/python2.7/site-packages/mptt/managers.py", line 63,
>in <module>` which maybe is related [to
>this](https://github.com/django-mptt/django-mptt/issues/378)?  Here is
>some maybe relevant context:
>
>```python
>63	class TreeManager(models.Manager.from_queryset(TreeQuerySet)):
>64	    """
>65	    A manager for working with trees of objects.
>66	    """
>67	
>68	    def contribute_to_class(self, model, name):
>69	        super(TreeManager, self).contribute_to_class(model, name)
>```
>
>I'm using Django 1.6.11 and this only happens when bringing up a dev VM
>for the first time.  Our established VM's seem to have no issue with
>this.  This lends me to believe there is an incompatible grey area of
>filer/mptt/polymorphic that a fresh build up of the `requirements.txt`
>that breaks.  Any ideas?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/divio/django-filer/issues/714

-- Inviato dal mio cellulare Android con K-9 Mail.

**Comment by chris-erickson** [comment]
Ok, well for what it's worth (and future searchers), this is a functional combination:

```
Django==1.6.11
django-filer==0.9.5
django-polymorphic==0.7.1  # 0.7.2 starts introducing problems
```
This pulls in `django-mptt==0.5.5`, but that could be dependent on other packages as well.
