### ISSUE TITLE
deprecation for the url patterns

### ISSUE THREAD

**Issue by rsunder10** [divio/django-filer#717]
/media/sunder/Work/ReviewOrb/lib/python3.4/site-packages/filer/admin/folderadmin.py:224: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='filer-directory_listing-unfiled_images'),

/media/sunder/Work/ReviewOrb/lib/python3.4/site-packages/filer/admin/clipboardadmin.py:58: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  name='filer-ajax_upload'),

**Comment by joshuajonah** [comment]
Kind of tough to fix something and test it in a software that doesn't exist yet.

**Comment by mattbriancon** [comment]
@joshuajonah actually it's not, `patterns` has been deprecated since 1.8; as per the warning's messages, uses of `patterns` needs to be replaced by a list.
