### ISSUE TITLE
Use filer as a tinymce attachments provider

### ISSUE THREAD

**Issue by frague59** [divio/django-filer#742]
Hi, 

Can I use filer as a tinyMCE (or another html / text editor) attachments provider ?

Thanks for your help !

**Comment by stefanfoulis** [comment]
@frague59 unfortunately such integration is a bit tricky. Most of these integration just end up inserting a specific url to a file into the editor. But in the case of django-filer, the url is not guaranteed to stay the same. If you change permissions or replace the file, it will get a new url.
So anything using filer files will have to reference the File object in the database and get the url from that dynamically.
I suspect that is something that would be hard to integrate in tinyMCE.

We have this implemented for the CKeditor used with the django-cms text plugin though.

**Comment by stefanfoulis** [comment]
feel free to re-open if you have more questions
