### ISSUE TITLE
display issues when djangocms-admin-style is not loaded

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#749]
These are using django-filer with Django 1.9 and without djangocms-admin-style

- [ ] header is too small
- [ ] action buttons not aligned nicely

<img width="1026" alt="screen shot 2016-02-24 at 09 17 58" src="https://cloud.githubusercontent.com/assets/14330/13279373/9d05a7d0-dad7-11e5-82de-850aa726817c.png">

**Comment by lory87** [comment]
@stefanfoulis issues are fixed
