### ISSUE TITLE
ui for folder picker widget not so pretty

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#770]
https://github.com/divio/django-filer/blob/600f0ffa59e1807063dfe5c5cc69d6971460b0d2/filer/templates/admin/filer/widgets/admin_folder.html

![screen shot 2016-03-07 at 13 57 19](https://cloud.githubusercontent.com/assets/14330/13570105/8a6d11c8-e46c-11e5-96ed-6d4091fed8f3.png)

![screen shot 2016-03-07 at 13 57 11](https://cloud.githubusercontent.com/assets/14330/13570107/8d4f550e-e46c-11e5-988f-00aec2a07dae.png)

**Comment by lory87** [comment]
@stefanfoulis this issue is fixed and merged to develop
