### ISSUE TITLE
folder listing has broken breadcrumbs

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#771]
![screen shot 2016-03-08 at 23 21 33](https://cloud.githubusercontent.com/assets/14330/13618476/8fdb7208-e584-11e5-9fbf-87a2a1f8affe.png)

should look more like
![screen shot 2016-03-08 at 23 21 48](https://cloud.githubusercontent.com/assets/14330/13618479/95e74258-e584-11e5-9871-9a6e8e2c7683.png)

Looks bad in Django 1.6 as well. So probably not because of a change in Django itself.

**Comment by lory87** [comment]
@stefanfoulis this issue is fixed and merged to develop.
https://github.com/divio/django-filer/pull/788
