### ISSUE TITLE
widgets show useless "edit" icon

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#777]
<img width="926" alt="screen shot 2016-03-09 at 09 17 27" src="https://cloud.githubusercontent.com/assets/14330/13629215/d650b18c-e5d7-11e5-9acf-9e4136b3c630.png">

The little yellow pen icon is non-functional (it comes from the raw id field we override). It should be hidden/removed.

djangocms-admin-style hides it on the Image and Folder widgets. But not on the File widget.

**Comment by stefanfoulis** [comment]
I'm not sure if this is a pure frontend issue in js/html/css. @lory87 let me know if I need to change something in the python code.

**Comment by lory87** [comment]
@stefanfoulis this is fixed and merged to develop
