### ISSUE TITLE
Minor version bump for RemovedInDjango110Warning fixes?

### ISSUE THREAD

**Issue by maltebeckmann** [divio/django-filer#780]
Could I bug you for a minor version bump to a stable version that doesn't have those RemovedInDjango110Warning warnings?

**Comment by yakky** [comment]
I don't think removing some warnings it's a reason to issue a release. Current develop contains a lot of changes for next feature version, and it must carefully planned along with cmsplugin-filer

**Comment by maltebeckmann** [comment]
Sure!
