### ISSUE TITLE
Errant migration added from byte literal

### ISSUE THREAD

**Issue by jschneier** [divio/django-filer#837]
Hi. Just installed 1.2 using Python 3.5 and if I run a blank `makemigrations` without specifying a package a new filer migration is added. This is due to the byte literal added in [migration 0004](https://github.com/divio/django-filer/blob/develop/filer/migrations/0004_auto_20160328_1434.py). My recommendation would be to simply remove the byte literal.

**Comment by yakky** [comment]
This has been fixed by 1.2.1
