### ISSUE TITLE
Image picker broken: No option to select image

### ISSUE THREAD

**Issue by frederik-elwert** [divio/django-filer#843]
I am using django-filer together with the django-cms plugins and ckeditor.

In 1.2.0, the image picker seems to be broken. Steps to reproduce:

1. Edit text plugin with ckeditor.
2. In the ckeditor menu, select *CMS Plugins → Image*
3. In the "Add CMS Plugin" dialog, click *Upload File*
4. The file browser view is opened, but there is no option to select the image and return to the plugin dialog. Previous versions (including 1.1.1) used to have this icon: 
![select_item](https://cloud.githubusercontent.com/assets/3049661/15159995/d350bf6c-16f7-11e6-993d-90bea50e7269.gif)
.

The screenshot shows the issue:

![filer-image-picker](https://cloud.githubusercontent.com/assets/3049661/15159931/6f28cdfe-16f7-11e6-80be-1e7d7c801ebd.png)

**Comment by lory87** [comment]
Hi @frederik-elwert Thank you for reporting this issue. We will let you know when the issue is fixed.

**Comment by lory87** [comment]
Hi @frederik-elwert 
I couldn't reproduce the issue. See enclosed screenshot. Can you please clear cache or give me more information about your project and django and cms version? Thank you for your feedback.

![screen shot 2016-05-18 at 09 58 35](https://cloud.githubusercontent.com/assets/2270884/15351505/df4a1596-1cdf-11e6-83e2-525f70353b47.png)

**Comment by frederik-elwert** [comment]
Hm, strange. I now tried to reproduce it, but indeed it works. In the buggy version, the file picker didn’t even open a new window, but altered the content of the modal in place. Maybe some issue with cached files?

Anyway, sorry for the fuzz.
