### ISSUE TITLE
KeyError in migration 0004 with custom/overridden FILER_IMAGE_MODEL 

### ISSUE THREAD

**Issue by aleehedl** [divio/django-filer#851]
Migration 0004_auto tries to alter a field on the Image model. As this model can be overridden with the FILER_IMAGE_MODEL setting it may not exist and produce a KeyError: ('filer', 'image') when the migration is run.

Proposal: check in the migration if FILER_IMAGE_MODEL is set and only do the operation if it is not. The same is done in migration 0001 with CreateModel for the Image model.

**Comment by FinalAngel** [comment]
thanks @aleehedl it has been fixed in https://github.com/divio/django-filer/pull/854

**Comment by aleehedl** [comment]
I'm sorry, but #854 does **not** fix this issue. This issue is about the overrideable FILER_IMAGE_MODEL and #854 does not check if it has been overridden or not.

**Comment by FinalAngel** [comment]
sorry about that then @aleehedl I'd be really happy if you re-open the PR than against the new issue and we'll merge :)

**Comment by aleehedl** [comment]
New PR #856
