### ISSUE TITLE
KeyError in migration 0004 and 0005 with custom/overridden FILER_IMAGE_MODEL

### ISSUE THREAD

**Issue by aleehedl** [divio/django-filer#855]
Migrations 0004_auto and 0005_auto alter a field on the Image model. As this model can be overridden with the FILER_IMAGE_MODEL setting it may not exist and produce a KeyError: ('filer', 'image') when the migration is run.

Proposal: check in the migration if FILER_IMAGE_MODEL is set and only do the operation if it is not. The same is done in migration 0001 with CreateModel for the Image model.

**Comment by stefanfoulis** [comment]
see #778

**Comment by stefanfoulis** [comment]
Closing since it is now fixed by #857 . Please re-open if it is still an issue.
