### ISSUE TITLE
Upload to defined folders

### ISSUE THREAD

**Issue by bee-keeper** [divio/django-filer#865]
Hi,

As per this [SO](url) question. - Is there a way to define which folder the image is uploaded to?  

I'm currently writing a migration to filer but with all the images going to unsorted, the admin interface become quickly unusable.

Thanks,

**Comment by yakky** [comment]
Each ``File`` has the ``folder`` attribute, which is the ``ForeignKey`` to a ``Folder`` instance.
You can create the folder structure and then assign the correct folder to each file in your migration code

**Comment by bee-keeper** [comment]
Ok thanks for this.
