### ISSUE TITLE
Dropping or uploading an image does not fire a change event

### ISSUE THREAD

**Issue by jrief** [divio/django-filer#888]
In order to adopt the behavior of some widgets, my library has to know, whether an image has been dropped into the Dragzone, uploaded or removed from the image uploader widget.

Would it be possible to trigger a ``changed`` event, whenever the field

```html
<input class="vForeignKeyRawIdAdminField" id="id_image_file" name="image_file" type="hidden" value="">
```

changes its value, so that I can bind on that event and adopt my widgets accordingly?

This would be quite simple by adding

```
inputId.trigger('changed')
```

behind the two occurrences ``inputId.val(...)`` in ``dropzone.init.js``

Shall I create a pull request for it?

**Comment by vxsx** [comment]
Closed via https://github.com/divio/django-filer/pull/889
