### ISSUE TITLE
Cannot add folder permission

### ISSUE THREAD

**Issue by petrklus** [divio/django-filer#892]
Setting added:

    FILER_ENABLE_PERMISSIONS = True

I can see the additional admin menu:

![image](https://cloud.githubusercontent.com/assets/1115667/16929041/103833fa-4d36-11e6-9e98-374f5a18a41f.png)

However, I am not able to select the anything in the popup window:

![image](https://cloud.githubusercontent.com/assets/1115667/16928979/d75fba08-4d35-11e6-8c99-a10332c3167e.png)

Is there any additional setting I am missing? I am on 1.1.1 but the same result is happening on the latest release.

**Comment by zypro** [comment]
@petrklus what was the issue? Facing same after upgrade.

**Comment by bhuiyanmobasshir94** [comment]
@petrklus you should click on the left arrow to choose the folder.
