### ISSUE TITLE
Weird error in polymorphic

### ISSUE THREAD

**Issue by sysint64** [divio/django-filer#897]
Hello, I get an error when I try to get list of images:
`'str' object has no attribute '_meta'`
I found where app falls - in polymorphic/query.py line 248 (symbol is _get_real_instances):
```
real_objects = real_concrete_class.base_objects.filter(**{
    ('%s__in' % pk_name): idlist,
})
```
if I replace this to
`real_objects = real_concrete_class.base_objects.all()`
all works fine...

**Comment by joshuajonah** [comment]
+1

**Comment by sysint64** [comment]
This not work for me :( very strange...

**Comment by patroqueeet** [comment]
I'm on Django 1.9 and Polymorphic 0.8.1 . Upgrading attempt to 1.9.9 and 1.0.1 did work for me.

**Comment by sysint64** [comment]
Yes thanks, I upgrade Django from 1.9 to 1.9.9 and now all works fine.
