### ISSUE TITLE
SubjectLocation (FocalPoint) sometimes only appears on second pageload

### ISSUE THREAD

**Issue by stefanfoulis** [divio/django-filer#9]

**Comment by lory87** [comment]
Hi @szuliq I can't reproduce this issue anymore in current filer version 1.2.0. Do you still have this problem? Thank you for your feedback.

**Comment by szuliq** [comment]
I will not be able to confirm this in a predictable time frame. Sorry.

Let's just assume it's working if you've checked with images that were loaded from browser's cache.

**Comment by lory87** [comment]
@szuliq I have checked and it works fine. I will close this issue. If you will find this problem again please let us know. Thank you.
