### ISSUE TITLE
No "Upload Image" Button in Popup

### ISSUE THREAD

**Issue by bculpepper** [divio/django-filer#902]
For some reason the "Upload File" button is missing from the popup generated from the "Add File" button click. I can drag and drop an image in the box without issue but I need the user to be able to click the "Upload File" button. Any ideas what could be causing this?

Filer Version: 1.1.1
Django Version: 1.9.5
Python Version 3.4

Model Code:
from filer.fields.image import FilerImageField
...

small_image = FilerImageField(related_name='small_image')
large_image = FilerImageField(related_name='large_image')

...

Attached are screen shots of what I am seeing.

Thanks in advance for the help!

Brandon Culpepper
![no-upload-button](https://cloud.githubusercontent.com/assets/711952/17596244/19afea4e-5fb6-11e6-8b0d-3f692702e697.jpg)
![add-file-field](https://cloud.githubusercontent.com/assets/711952/17596245/19b01bcc-5fb6-11e6-9dbe-39570457ef9f.jpg)

**Comment by benzkji** [comment]
you can not upload to the root?? try creating a folder, then it should appear...?

**Comment by benzkji** [comment]
I agree, if dropping a file is possible (goes into "unfiled files"), the same should be possible for normal uploads...

**Comment by bculpepper** [comment]
That worked! Adding a folder made the Upload File button appear. Thank you so much for the tip. It is strange that the drag and drop allows for upload to unfiled files, though.

Thanks again!

**Comment by FinalAngel** [comment]
You first have to create a folder to upload it. Once a folder is selected the upload button is shown. Otherwise all uploads go to "Unfiled files".

**Comment by benzkji** [comment]
either disable upload button AND dropping files, or enable both, would be the clean solution?

**Comment by bculpepper** [comment]
I agree with @benzkji
