### ISSUE TITLE
Limit default number of file upload widgets visible in admin model? 

### ISSUE THREAD

**Issue by ntorek** [divio/django-filer#906]
I am trying to implement django-filer file upload into my admin model. It seems to be working fine except for the fact that I can see too many multiple file upload widgets when I create a new record in model admin. Each time I upload a new file, it adds another widget, so I always have several extra ones. Is there a way to limit the number of upload widgets that show up by default, so the user can just see, say, 1 extra widget, and then click "Add another file" when they want to add another file? Here is a screenshot of what I am currently seeing. Thank you!
<img width="1227" alt="screen shot 2016-08-12 at 12 11 15 pm" src="https://cloud.githubusercontent.com/assets/20539911/17630386/0acc033c-608d-11e6-9481-d92ee5e1a59c.png">

**Comment by zodman** [comment]
try using

https://docs.djangoproject.com/es/1.10/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.max_num

Its not related to django-filer

**Comment by yakky** [comment]
@ntorek @zodman agree. Using max_num / extra will solve this.
Closing
