### ISSUE TITLE
Image _width and _height are NULL after import from fixture

### ISSUE THREAD

**Issue by jrief** [divio/django-filer#965]
How to reproduce:

On a site with images

```
./manage.py dumpdata filer.Image > images.json
./manage.py loaddata images.json
```

check the database, in table ``filer_image`` fields ``_width`` and ``_height`` are NULL after the import, whereas the fixture contains the correct sizes.

One workaround is to reset the sizes with this simple script

```
from filer.models.imagemodels import Image

for img in Image.objects.all():
    img.file_data_changed()
    img.save()
```

Used versions:
Django==1.10.5
django-filer==1.2.6

**Comment by jrief** [comment]
After investigating this, I saw that the fields ``_width`` and ``_height`` (which contain valid data) are set  to ``None`` in https://github.com/divio/django-filer/blob/develop/filer/models/abstract.py#L69 while loading the fixture.

Why can't we just leave these values as is? Then this bug would not happen.

**Comment by jrief** [comment]
would be great to bump to version 1.2.8 which fixes this problem

**Comment by jrief** [comment]
Ping
with django-CMS version 3.4.4 it would be really useful, if we also get a new version of django-filer

**Comment by stefanfoulis** [comment]
@jrief 1.2.8 has been released. Sorry for the delay.
