### ISSUE TITLE
search ui is off on a fresh installation with django 1.10

### ISSUE THREAD

**Issue by xrmx** [divio/django-filer#971]
With firefox on a new django filer installation the search box looks a bit off:

![broken-ui-ff](https://cloud.githubusercontent.com/assets/12932/23748900/dd748da4-04c5-11e7-9046-521e2390410f.png)

django 1.10.6, django-filer 1.2.7

**Comment by hnk** [comment]
Duplicate of #956

**Comment by xrmx** [comment]
@hnk thanks!
