### ISSUE TITLE
Your library have problem when it is used inside the Django-Admin as Inline ( admin.TabularInline ), only detects initial drop-zones

### ISSUE THREAD

**Issue by raymondSeger** [divio/django-filer#986]
Your library have problem when it is used inside the Django-Admin as Inline ( admin.TabularInline. etc) objects. New object that have FilerImage shows the drop-zone, but it does not work, it only works if i save the page first or i add this script:

<script>
(function($){

    window.make_drop_box_works = function() {
        $('.filer-dropzone').each(function( index, el ) {
            try {
                $(el).dropzone({
                    url: $( el ).data('url')
                })
            } catch(exception) {

            }
        });
    };
    setInterval(make_drop_box_works, 3000);
})(jQuery);
</script>

with that script, it can suddenly receive file through drag and drop, BUT despite the success info, it actually fails, it does not send the data. But when i tried it again, it suddenly works. Basically the problems seems to be the drop-zone only "get" the initial drop-zones, dynamic drop-zones that are added are not "detected".

How do i fix this? thanks

**Comment by blablacio** [comment]
It's fixed in #981

**Comment by raymondSeger** [comment]
how do i use the fix? Thanks

**Comment by raymondSeger** [comment]
thanks! i got it
