### ISSUE TITLE
allow easy way to set UPLOAD_TO method

### ISSUE THREAD

**Issue by benzkji** [divio/django-filer#991]
if one only wants to override the `UPLOAD_TO` method, for a storage, the complete `FILER_STORAGES` dict must be set in own settings. this can be very frustrating, as it is sensible, can break things easily, and is not that well documented. for example, I dont know if the example in the docs are the actual defaults and can be copy pasted and afterwards adapted (dont think so, as it "didnt work" this way). Also, reading `filer.settings.py` reveals a lot of complicated setup code, ...(removed the further rant ;-).

**Comment by benzkji** [comment]
actually, setting this seems to work, due to the intense settings checking in `filer/settings.py`:

    FILER_STORAGES = {
        'public': {
            'main': {
                'UPLOAD_TO': 'filer_addons.filer_utils.generate_folder_and_filename.short_uuid4',
            },
        },
        'private': {
            'main': {
                'UPLOAD_TO': 'filer_addons.filer_utils.generate_folder_and_filename.short_uuid4',
            },
        },
    }

is it ok to do it like this?

**Comment by yakky** [comment]
@benzkji that's correct. Keys are merged into the default settings
I agree we can improve the documentation to say that you can just override single subkeys

Any suggestion on a clear phrasing is well accepted
